### PR TITLE
Removes incorrect decode which fails in Python 3.

### PR DESCRIPTION
**Pull request by jruere**

### CODE REVIEW

**Comment by cecton** [comment]
Actually, good remark from a friend.

Is it correct?
How this things didn't break the tests?
Is it actually tested?
Can you improve the tests so it runs in this code?

In the meantime, I will add integration tests on this repository.

**Comment by jruere** [comment]
> Is it correct?
What a question. Who knows!
Magic returns a str object in Python 2 and 3. It works in Python 2 because it has the method but not on 3.
I believe the Python 3 behaviour is correct.

> How this things didn't break the tests?
It does break the tests if you test in Python 3. I get 13 errors.

> Is it actually tested?
The Guesser has tests.

> Can you improve the tests so it runs in this code?
Tox could be implemented to test against several versions but that would be a separate change.

**Comment by cecton** [comment]
Everything works fine with the version 0.4.11 of python-magic. If you need a fix quickly, I suggest you to downgrade. In the meantime I will set up the integration test (and fix the version of python-magic in the setup.py for now).

**Comment by cecton** [comment]
Actually I published it on pypi already. You can upgrade your package and it should fix the dependency issue. I will merge your fix when I will have integration tests working.

**Comment by cecton** [comment]
Thanks @jruere for having reveal this bug.

**Pull request closed without merging**
